### ISSUE TITLE
Failed to load the library

### ISSUE THREAD

**Issue by ghostjat** [Letargie/pggi#6]
`
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/ghost/Documents/php-bin/gui/pggi/modules/pggi.so' - /home/ghost/Documents/php-bin/gui/pggi/modules/pggi.so: undefined symbol: zend_string_init_interned in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/ghost/Documents/php-bin/gui/pggi/modules/pggi.so' - /home/ghost/Documents/php-bin/gui/pggi/modules/pggi.so: undefined symbol: zend_string_init_interned in Unknown on line 0

=====================================================================
PHP         : /usr/local/php7/bin/php 
Warning: PHP Startup: Unable to load dynamic library '/home/ghost/Documents/php-bin/gui/pggi/modules/pggi.so' - /home/ghost/Documents/php-bin/gui/pggi/modules/pggi.so: undefined symbol: zend_string_init_interned in Unknown on line 0

PHP_SAPI    : cli
PHP_VERSION : 7.1.9RC1
ZEND_VERSION: 3.1.0
PHP_OS      : Linux - Linux ghost-G580 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:12:19 UTC 2018 i686
INI actual  : /home/ghost/Documents/php-bin/gui/pggi/tmp-php.ini
More .INIs  :   
CWD         : /home/ghost/Documents/php-bin/gui/pggi
Extra dirs  : 
VALGRIND    : Not used
`

**Comment by remicollet** [comment]
I cannot reproduce... Build + examples ok with 7.0.30 / 7.1.18 / 7.2.7

**Comment by remicollet** [comment]
Notice: zend_string_init_interned is a new PHP 7.2 symbol, so this should not happen with PHP 7.1

* Ensure you build against the same version that you run the extension
* `make clean` before `make` may help

**Comment by ghostjat** [comment]
Still having same problem

**Comment by zababurinsv** [comment]
[27-Apr-2019 17:54:56] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/memcached/modules/memcached.so' - /usr/local/memcached/modules/memcached.so: undefined symbol: zend_string_init_interned in Unknown on line 0

**Comment by Letargie** [comment]
It just seems that your memcached isn't in the same version as your php.
